version: "2"

services:

  api: &api
      build: ./api
      depends_on:
          - db
      volumes:
          # Use the locally mounted volume for local development
           - api-build-volume:/src
#          - ./api:/src
      ports:
          - "80"
      entrypoint: /usr/local/bin/npm
      command: start
      environment:
          DEMO_APP_DOCKER_IP: "${DEMO_APP_DOCKER_IP}"

  api-ut:
    <<: *api
    command: test

  ui:
      build: ./ui
      volumes:
        # Use the locally mounted volume for local development
        - ui-build-volume:/usr/share/nginx/html
#        - ./ui/build:/usr/share/nginx/html
      ports:
          - "80"
  
  bbt:
    build: ./bbt
    depends_on:
      - nginx

  nginx:
      build: ./nginx
      depends_on:
          - api
          - ui
      ports:
          - "8088:8088"
  db:
      image: mongo:3.0
      command: mongod --smallfiles
      restart: always
      ports:
          - "27017"
  package:
    build: ./package
    volumes:
      # Volumes for building UI
      - ./ui:/app/ui/source
      - ui-build-volume:/app/ui/build
      # Volumes for build the api dependencies
      - ./api:/app/api/source
      - api-build-volume:/app/api/build

volumes:
  ui-build-volume:
  api-build-volume:
